# Site settings
title: "Rachel & Alex - July 9th, 2016 - Peaks Island, Portland, ME"
description: > 
  The Mekelhammer wedding website.
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
